name: "The Makers' Almanac"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32665543467737734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6530279491562396
  lightness: 0.9527796632610261
  saturation: 0.6957319620996714
  rhythmicContrast: 0.17462377552874386
purpose: []
